### ISSUE TITLE
Activate SSL/TLS certificates chain of trust verification.

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx-give-payfast-gateway#5]
Set value to true. 

https://github.com/lightspeeddevelopment/lsx-give-payfast-gateway/blob/cf579eed1353dffb8fa900c36c1cca52d207f8be/classes/class-give-recurring-payfast.php#L215

**Comment by JosephLightSpeed** [comment]
@eleshar this has been set to true and committed https://github.com/lightspeeddevelopment/lsx-give-payfast-gateway/commit/9f7fe2b8cc639d797f357eb89a65cb24d16a2929. 

Closing this off.
