### ISSUE TITLE
Avoid MD5 Hash Functions

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx-give-payfast-gateway#6]
The MD5 cryptographic algorithms are considered insecure, and should be replaced with new and more performant algorithms. I would recommend Argon2ID, Argon 2I or BCrypt. Note that Argon2 would require PHP7.2+.

https://github.com/lightspeeddevelopment/lsx-give-payfast-gateway/blob/9f7fe2b8cc639d797f357eb89a65cb24d16a2929/classes/class-give-recurring-payfast.php#L200

https://github.com/lightspeeddevelopment/lsx-give-payfast-gateway/blob/9f7fe2b8cc639d797f357eb89a65cb24d16a2929/give-payfast.php#L110

https://github.com/lightspeeddevelopment/lsx-give-payfast-gateway/blob/9f7fe2b8cc639d797f357eb89a65cb24d16a2929/give-payfast.php#L164

https://github.com/lightspeeddevelopment/lsx-give-payfast-gateway/blob/9f7fe2b8cc639d797f357eb89a65cb24d16a2929/give-payfast.php#L166

https://github.com/lightspeeddevelopment/lsx-give-payfast-gateway/blob/9f7fe2b8cc639d797f357eb89a65cb24d16a2929/give-payfast.php#L234

**Comment by krugazul** [comment]
@eleshar unfortunately we need to use the same hash that [payfast](https://developers.payfast.co.za/documentation/#getting-started) does on their side to generate a matching signature.  We cant change this too another hash.
