### ISSUE TITLE
Error : unable to process subscription donations with PayFast

### ISSUE THREAD

**Issue by paulka007** [lightspeeddevelopment/lsx-give-payfast-gateway#8]
With the recurring plugin enabled, and only when selecting to make a donation recurring the following error appears on the donation form screen:

Error: Sorry we're unable to process subscription donations with PayFast. Please switch to either the payment gateways to process a subscription donation.

**Comment by krugazul** [comment]
I have finally manage to fix the signature mismatch, as well as the recurring billing not being included.  The code has been added to the master branch,  and will be available in the release today.
